org.gradle.jvmargs=-Xmx2048m
android.useAndroidX=false
android.nonTransitiveRClass=true

# This connection times out on Google's Maven with Gradle's 30s default.
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000
systemProp.org.gradle.internal.repository.max.retries=10
systemProp.org.gradle.internal.repository.initial.backoff=1000
